name: Continuous Integration
on:
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check format
        run: |
          cargo fmt \
          --all \
          --check \
          --verbose
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Lint
        run: |
          cargo clippy \
          --all-targets \
          --verbose \
          -- \
          -Dclippy::all \
          -Dclippy::cargo \
          -Dclippy::pedantic \
          -Dmissing_docs
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: |
          RUSTFLAGS=-Dwarnings \
          cargo build \
          --all-targets \
          --locked \
          --verbose
      - name: Test
        run: |
          RUSTFLAGS=-Dwarnings \
          cargo test \
          --all-targets \
          --locked \
          --no-fail-fast \
          --verbose
